name: Laravel Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  laravel:
    runs-on: ubuntu-latest

    steps:
      # {1} Checkout the source code
      - name: Checkout the source code
        uses: actions/checkout@v4

      # {2} Setup PHP
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pgsql

      # {3} Copy .env
      - name: Copy .env
        run: php -r "file_exists('.env') || copy('.env.example', '.env');"

      # {4} Install Composer dependencies
      - name: Install Composer dependencies
        run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

      # {6} Set Directory Permissions
      - name: Directory Permissions
        run: chmod -R 777 storage bootstrap/cache

      # {7} Set up SSH Agent with private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      # {8} Deploy to server using SSH
      - name: executing remote ssh commands using key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }} # hostname of the server
          username: ${{ secrets.USERNAME }} # username to login to the server
          port: ${{ secrets.PORT }} # port of the server, often 22
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /var/www/html/myLaravel # navigate to your project directory
            sudo git config --global --add safe.directory /var/www/html/myLaravel
            sudo git stash
            sudo git fetch --all
            sudo git pull origin main

            sudo chown -R www-data:www-data /var/www/html/myLaravel
            sudo chmod -R 755 /var/www/html/myLaravel

            composer install --prefer-dist --no-progress --optimize-autoloader

            sudo php artisan migrate --force
            sudo php artisan config:cache
            sudo php artisan route:cache
            sudo php artisan view:cache

            sudo systemctl restart nginx

